name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"  # Runs daily at midnight UTC
  workflow_dispatch:     #  to run the workflow manually

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Generate Snake Animation
        uses: Platane/snk@master
        with:
          github_user_name: <Anshul-B-A>  # Replace with GitHub username
          output: dist/snake.svg

      - name: Push the generated snake animation to the repository
        uses: ad-m/github-push-action@v0.6.0
        with:
          branch: master
          file: dist/snake.svg

